apiVersion: v1
kind: ConfigMap
metadata:
  name: basf-mongo-config
data:
  host: basf-mongo-bd
  database: basfbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: basf-mongodb-service
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basf-challenge
  name: basf-challenge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basf-challenge
  template:
    metadata:
      labels:
        app: basf-challenge
    spec:
      containers:
        - image: lperilla/challenges:basf-challenge
          name: basf-challenge
          volumeMounts:
            - mountPath: /applis/basf
              name: basf-storage
      volumes:
        - name: basf-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: basf-challenge-service
  name: basf-challenge-service
spec:
  type: ClusterIP
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: basf-challenge
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basf-challenge-ingress
spec:
  rules:
  - http:
      paths:
      - path: /graphiql
        pathType: Prefix
        backend:
          service:
            name: basf-challenge-service
            port:
              number: 8080