server:
  port: 8080
  servlet:
    context-path: /basf-challenge
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/basfbd
      database: basfbd
      port: 27017
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql
    cors-enabled: false
    # cors:
    #  allowed-origins: http://some.domain.com
    #  allowed-methods: GET, HEAD, POST
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    # Sets if asynchronous operations are supported for GraphQL requests. If not specified defaults to true.
    async:
      enabled: true
  graphiql:
    mapping: /graphiql
    endpoint:
      graphql: /graphql
      subscriptions: /subscriptions
    subscriptions:
      timeout: 30
      reconnect: false
    basePath: /
    enabled: true
    pageTitle: GraphiQL
    cdn:
      enabled: false
      version: latest
basf:
  directory: /tmp/basf-challenge